### PR TITLE
Dev/fix slow qr scanner

### LINKED ISSUE #1147: Scanning QR codes is really slow on mobile

### PR DESCRIPTION
**Pull request by tanx**
Closes #1147

### CODE REVIEW

File: src/component/qrcode-scanner.js [hunk 1]
```diff
@@ -41,8 +42,13 @@ export default class QRCodeScanner extends React.Component {
     this.setState({ hasCameraPermission: status === 'granted' });
   }
 
+  handleCodeScanned({ type, data }) {
+    this.setState({ scanned: true });
+    this.props.onQRCodeScanned({ type, data });
```
Comment (valentinewallace) [inline src/component/qrcode-scanner.js]: Seems you could just pass `data` and not `type`?

Comment (tanx) [reply src/component/qrcode-scanner.js]: Yeah we only use `data`. But no need to remove type from the QR component. Maybe the component will be used somewhere we need type later.

**Comment by tanx** [comment]
> Fwiw I'm unable to repro this issue 🤔 is it Android specific?

Did you test on mainnet? It wasn't an issue on testnet since querying the route was faster. Likely due to a much smaller network.
