### PR TITLE
Dev/fix home balance font size

### LINKED ISSUE #879: Resize balance label to fit screen width on mobile (home screen)
@valentinewallace on iOS we can use https://facebook.github.io/react-native/docs/text#adjustsfontsizetofit

Let's ignore Android for now.

### PR DESCRIPTION
**Pull request by tanx**
Closes #879 

Used Lee's updated design to allow `Text.adjustsfontsizetofit`:

image

### CODE REVIEW

File: src/store.js [hunk 1]
```diff
@@ -94,7 +94,7 @@ export class Store {
       settings: {
         unit: DEFAULT_UNIT,
         fiat: DEFAULT_FIAT,
-        displayFiat: true,
+        displayFiat: false,
```
Comment (valentinewallace) [inline src/store.js]: So bold

**Comment by tanx** [comment]
> tACK, works great!
> 
> I'm getting this warning, but I can't figure out why because it seems like the `prop` is a string:

@valentinewallace good catch. Fixed this in https://github.com/lightninglabs/lightning-app/pull/1295/commits/8305fffc380bf4de5585baab296009c419a23ea0
