### PR TITLE
Fix unified balance

### LINKED ISSUE #1016: Pending-open balance is being added to unifued balance twice
We need to remove `pendingBalanceSatoshis` from ComputedWallet.totalBalanceSatoshis()

https://github.com/lightninglabs/lightning-app/blob/4c586796ca9bf4ee2cbb585178fa81cb252691dd/src/computed/wallet.js#L19-L32

### PR DESCRIPTION
**Pull request by tanx**
Closes #1016

### CODE REVIEW

**Comment by tanx** [comment]
@valentinewallace this on relies on #1156

File: src/computed/wallet.js [hunk 1]
```diff
@@ -17,22 +17,22 @@ const ComputedWallet = store => {
       return store.walletAddress ? `bitcoin:${store.walletAddress}` : '';
     },
     get balanceLabel() {
-      return toAmountLabel(store.balanceSatoshis, store.settings);
+      return toAmountLabel(store.confirmedBalanceSatoshis, store.settings);
     },
     get totalBalanceSatoshis() {
       const {
-        balanceSatoshis: onChainBalanceSatoshis,
+        confirmedBalanceSatoshis: onChainBalanceSatoshis,
```
Comment (valentinewallace) [inline src/computed/wallet.js]: Clarifying variable rename :+1:

**Comment by tanx** [comment]
> I think it looks good. So, we were adding the pending force close balance but we should've been adding the total pending close balance?

The problem was that `waiting close` balance was being added in addition to `pending open` balances from autopilot. Since we set autopilot to wait until 1 conf to open new channels this is no longer an issue. This change makes things a lot more resilient in general. This is what @Roasbeef was also mentioning.
