### PR TITLE
Fix pending deposit

### LINKED ISSUE #468: Display correct pending deposit on home screen
We should probably add `pending_open_balance` to pending deposit...

@roasbeef:
noticed ealier that there may be a gap in how we display balances to the user atm
as we don't display the pending balance from the call: https://api.lightning.community/#channelbalance
so if we open a channel, and it hasn't yet been confirmed, then the two balances we display won't add up atm
by default the total_balance in wallet balance will sum the two 
but the balance that's from ChanneBalance actually won't as we don't display a sum of the two

### PR DESCRIPTION
**Pull request by tanx**
Closes #468

### CODE REVIEW

File: src/view/home.js [hunk 1]
```diff
@@ -56,7 +56,7 @@ const HomeView = ({
       <QrCodeSeparator goDeposit={() => nav.goDeposit()} />
       <MainContent style={styles.content}>
         <BalanceDisplay
-          balanceLabel={balanceLabel}
+          depositLabel={depositLabel}
```
Comment (valentinewallace) [inline src/view/home.js]: suggestion: `depositLabel` --> `pendingDepositLabel`?

Comment (tanx) [reply src/view/home.js]: If there were multiple depositLabels. But short names are good names :)
