### PR TITLE
Fix bug such that if the app crashes while a user is restoring a wall…

### LINKED ISSUE #757: Handle app crash/quit before completion of recovery process
Currently, if a recovery is started but the app quits before it completes, then the app is unlocked, it won't properly go back into recovery mode. 

So there should be some persistence of the fact that the recovery did not complete, such that the next time we start the app we can set the `recovery_window` option during wallet unlock (so the backend knows to continue the recovery rescan).

### PR DESCRIPTION
**Pull request by valentinewallace**
…et, restoration will resume upon app restart.

Closes #757.

### CODE REVIEW

**Comment by tanx** [comment]
@valentinewallace rather than introducing complexity by adding addition state to work around the issue. I'd suggest we solve the underlaying issue.

File: src/action/app-storage.js [hunk 1]
```diff
@@ -44,6 +48,10 @@ class AppStorage {
     try {
       const state = JSON.stringify(this._store.settings);
       await this._AsyncStorage.setItem('settings', state);
+      await this._AsyncStorage.setItem(
+        'restoringWallet',
+        this._store.wallet.restoring
+      );
```
Comment (tanx) [inline src/action/app-storage.js]: We currently only persist the settings object and should keep it that way for consistency's sake. If additional attributes are added, they should be added on the settings object.

File: src/action/info.js [hunk 2]
```diff
@@ -38,6 +38,7 @@ class InfoAction {
         });
         this._store.percentSynced = this.calcPercentSynced(response);
       } else {
+        this._store.wallet.restoring = false;
```
Comment (tanx) [inline src/action/info.js]: When is `store.wallet.restoring` set to true?

File: src/action/wallet.js [hunk 3]
```diff
@@ -403,6 +403,7 @@ class WalletAction {
       this._nav.goWait();
       await this._grpc.sendUnlockerCommand('UnlockWallet', {
         walletPassword: toBuffer(walletPassword),
+        recoveryWindow: this._store.wallet.restoring ? 250 : 0,
```
Comment (tanx) [inline src/action/wallet.js]: Perhaps I'm missing something, but won't `recoveryWindow ` always be `0`since `store.wallet.restoring` is never set to true?

File: src/action/app-storage.js (hunk 1 above)
Comment (valentinewallace) [reply src/action/app-storage.js]: Changed `restoring` to live in the `settings` part of the `store`.

File: src/action/info.js (hunk 2 above)
Comment (valentinewallace) [reply src/action/info.js]: On the `select-seed` view, when the user selects that they're restoring a wallet.

File: src/action/app-storage.js [hunk 4]
```diff
@@ -26,6 +26,9 @@ class AppStorage {
         if (typeof this._store.settings[key] !== 'undefined') {
           this._store.settings[key] = state[key];
         }
+        if (key === 'restoring') {
+          this._store.settings[key] = JSON.parse(state[key]);
+        }
```
[the remark this answers is not in the document]
Comment (valentinewallace) [reply src/action/app-storage.js]: Otherwise the property is parsed as a string, so this "casts" it to a boolean.

File: src/action/info.js (hunk 2 above)
Comment (valentinewallace) [reply src/action/info.js]: Yes, sorry thought i fixed that

File: src/action/setting.js [hunk 5]
```diff
@@ -56,6 +56,14 @@ class SettingAction {
...
     }
   }
+
+  /**
+   * Set whether or not we're restoring the wallet.
+   * @param {boolean} options.restoring Whether or not we're restoring.
+   */
+  setRestoringWallet({ restoring }) {
+    this._store.settings.restoring = restoring;
+  }
```
[the remark this answers is not in the document]
Comment (valentinewallace) [reply src/action/setting.js]: fixed

File: src/action/app-storage.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (valentinewallace) [reply src/action/app-storage.js]: Is there a better way? :grimacing:

[the remark this answers is not in the document]
Comment (tanx) [reply src/action/app-storage.js]: > Otherwise the property is parsed as a string, so this "casts" it to a boolean.

Really? Why was that not an issue with `store.settings.displayFiat`? I mean the JSON is already parse in line 24? Or am I missing something?
