### PR TITLE
Fix iphone xs bottom color

### LINKED ISSUE #846: Fix lower background color in transaction detail and logs view

### PR DESCRIPTION
**Pull request by tanx**
Closes #846 

@valentinewallace this fixes the bottom background color on the iPhone XS.

### CODE REVIEW

File: src/view/transaction-detail-mobile.js [hunk 1]
```diff
@@ -40,12 +40,13 @@ const styles = StyleSheet.create({
...
 
 const TransactionDetailView = ({ store, nav }) => (
-  <Background
+  <SplitBackground
     image={
       store.selectedTransaction.type === 'bitcoin'
         ? 'orange-gradient-bg'
         : 'purple-gradient-bg'
     }
+    bottom={color.whiteBg}
```
Comment (valentinewallace) [inline src/view/transaction-detail-mobile.js]: To me this line doesn't do anything... So the problem this PR solves is only on the iphone XS?

Comment (tanx) [reply src/view/transaction-detail-mobile.js]: > To me this line doesn't do anything... To clarify, the problem this PR solves is only on the iphone XS?

Oh sorry. Forgot to link the issue #846. This fixes the orange bar below the SafeAreaView.

**Comment by tanx** [comment]
> To me, this PR doesn't change anything. But, it also doesn't hurt anything. Am I supposed to be seeing a difference? If not, feel free to merge.

I couldn't post a screenshot here for some reason. Sent it on app-dev on keybase. Ok merging.
