### PR TITLE
Auth mobile

### LINKED ISSUE #607: Implement Password Incorrect mobile screen
https://invis.io/MRNSA11DFJH

### LINKED ISSUE #778: Use Expo SecureStore and Fingerprint apis to secure wallet password on mobile
https://docs.expo.io/versions/v31.0.0/sdk/securestore

https://docs.expo.io/versions/v28.0.0/sdk/fingerprint

### PR DESCRIPTION
**Pull request by tanx**
Closes #778, closes #607 

N.B. before we use this in production we need to fix https://github.com/lightninglabs/lightning-app/issues/777

### CODE REVIEW

**Comment by tanx** [comment]
@valentinewallace I created an issue to fix the breaking build. It's out of scope for this PR though: https://github.com/lightninglabs/lightning-app/issues/784

File: mobile/main.js [hunk 1]
```diff
@@ -1,5 +1,5 @@
 /**
- * @fileOverview The main module that wires up all depdencies for mobile.
+ * @fileOverview the main module that wires up all depedencies for mobile.
```
Comment (valentinewallace) [inline mobile/main.js]: lol, nit: `s/depedencies/dependencies`

File: src/view/wait-mobile.js [hunk 2]
```diff
@@ -21,6 +27,7 @@ const WaitView = () => (
         color={color.lightPurple}
         style={styles.spinner}
       />
+      <Text style={styles.copy}>Loading network...</Text>
```
Comment (valentinewallace) [inline src/view/wait-mobile.js]: Very good :ok_hand:

File: src/action/auth-mobile.js [hunk 3]
```diff
@@ -0,0 +1,202 @@
...
+   * Check the PIN that was chosen by the user was entered
+   * correctly twice to make sure that there was no typo.
+   * If everything is ok, store the pin in the keystore and
+   * unlock the wallet.
+   * @return {Promise<undefined>}
+   */
+  async checkNewPin() {
+    const { newPin, pinVerify } = this._store.auth;
+    if (newPin.length !== PIN_LENGTH || newPin !== pinVerify) {
+      this._alert('Incorrect PIN', () => this.initSetPin());
```
Comment (valentinewallace) [inline src/action/auth-mobile.js]: I liked in the previous commit in this PR where it told the user when the PINs did not match. Maybe we could switch to that error message -- is it possible for them to enter a pin of less than the correct length, since it won't let them go to the next screen otherwise?

File: src/action/auth-mobile.js [hunk 4]
```diff
@@ -0,0 +1,202 @@
...
+   * or a fingerprint reader on Android.
+   * @return {Promise<undefined>}
+   */
+  async tryFingerprint() {
+    const hasHardware = await this._Fingerprint.hasHardwareAsync();
+    if (!hasHardware) {
+      return;
+    }
+    const msg = 'Unlock your Wallet';
+    const { success } = await this._Fingerprint.authenticateAsync(msg);
```
Comment (valentinewallace) [inline src/action/auth-mobile.js]: Can confirm that fingerprint auth works on Android!!

**Comment by valentinewallace** [comment]
> @valentinewallace I created an issue to fix the breaking build. It's out of scope for this PR though: #784

SGTM!

File: src/action/auth-mobile.js [hunk 5]
```diff
@@ -0,0 +1,202 @@
...
+  //
+  // TouchID & KeyStore Authentication
+  //
+
+  /**
+   * Try authenticating the user using either via TouchID/FaceID on iOS
+   * or a fingerprint reader on Android.
+   * @return {Promise<undefined>}
+   */
+  async tryFingerprint() {
```
[the remark this answers is not in the document]
Comment (tanx) [reply src/action/auth-mobile.js]: If the device supports it the native OS UI will already display copy...

img_5921

File: src/action/auth-mobile.js (hunk 3 above)
Comment (tanx) [reply src/action/auth-mobile.js]: > I liked in the previous commit in this PR where it told the user when the PINs did not match. Maybe we could switch to that error message

Ok. I changed it back.

> is it possible for them to enter a pin of less than the correct length, since it won't let them go to the next screen otherwise?

Nope. The check only happens when all six bubbles are filled.

File: mobile/main.js (hunk 1 above)
Comment (tanx) [reply mobile/main.js]: Fixed.

File: src/action/auth-mobile.js (hunk 4 above)
Comment (tanx) [reply src/action/auth-mobile.js]: Nice. Did you get that iOS device yet?

File: src/action/auth-mobile.js (hunk 5 above)
[the remark this answers is not in the document]
Comment (valentinewallace) [reply src/action/auth-mobile.js]: Ah, not on Android. I just tried it and it worked

[the remark this answers is not in the document]
Comment (tanx) [reply src/action/auth-mobile.js]: Ok cool. I try to write the code so that it at least runs on Android, but I think we can ignore Android specific issues and focus on iOS for now.
